from math import *
from random import * #import all
from time import *
from datetime import *
result=ceil(4.6)
print(result)
result1=floor(4.6)
print(result1)
result2=fabs(-4.6)
print(result2)
result3=factorial(5)
print(result3)
result4=fmod(5,2)
print(result4)
result5=fsum([1,2,3,4,5])
print(result5)
result6=gcd(12,8)
print(result6)
result7=exp(2)
print(result7)
result8=log(2)
print(result8)
result9=log10(2)
print(result9)
result10=pow(2,3)
print(result10)
result11=sqrt(4)
print(result11)
result12=degrees(2)
print(result12)
result13=radians(2)
print(result13)
result14=sin(2)
print(result14)
result15=cos(2)
print(result15)
result16=tan(2)
print(result16)
# result17=asin(2)
# print(result17)
# result18=acos(2)
# print(result18)
# result19=atan(2)
# print(result19)
result20=sinh(2)
print(result20)
result21=cosh(2)
print(result21)
result22=tanh(2)
print(result22)
# result23=asinh(2)
# print(result23)
# result24=acosh(2)
# print(result24)
# result25=atanh(2)
# print(result25)
result26=erf(2)
print(result26)
print(random())
print(randint(1,10))
print(uniform(1,10))
print(randrange(1,10))
print(choice([1,2,3,4,5,6,7,8,9]))
print(sample([1,2,3,4,5,6,7,8,9],3))
print(time())
print(time_ns())
print(localtime())
print(asctime())
print(mktime(localtime()))
print(strftime("%Y-%m-%d %H:%M:%S",localtime()))
print(datetime.now())
print(datetime.today())
print(datetime.now().year)
print(datetime.now().month)
print(datetime.now().day)
print(datetime.now().hour)
print(datetime.now().minute)
print(datetime.now().second)
print(datetime.now().microsecond)
print(datetime.now().date())
print(datetime.now().time())
print(datetime.now().ctime())
print(datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print(datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f"))
print(datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f %Z"))

